// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9u7HhbPGZ6DT2tLVSjIlzMpT24qtirVM',
    appId: '1:705843360963:web:ff6cc99f76a675d48a5e76',
    messagingSenderId: '705843360963',
    projectId: 'my-ica-3101',
    authDomain: 'my-ica-3101.firebaseapp.com',
    storageBucket: 'my-ica-3101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RCCT0WYwJAls44_-A1soRxhm_pGAfOY',
    appId: '1:705843360963:android:f007d39bde8331dd8a5e76',
    messagingSenderId: '705843360963',
    projectId: 'my-ica-3101',
    storageBucket: 'my-ica-3101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2J_b_jtN07AFji4VXHummkF90xuwWBQ8',
    appId: '1:705843360963:ios:d5bde8c921f873e48a5e76',
    messagingSenderId: '705843360963',
    projectId: 'my-ica-3101',
    storageBucket: 'my-ica-3101.firebasestorage.app',
    iosClientId: '705843360963-p70qu8i63qjekls2kmub1jp3pve1gg3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.icaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2J_b_jtN07AFji4VXHummkF90xuwWBQ8',
    appId: '1:705843360963:ios:d5bde8c921f873e48a5e76',
    messagingSenderId: '705843360963',
    projectId: 'my-ica-3101',
    storageBucket: 'my-ica-3101.firebasestorage.app',
    iosClientId: '705843360963-p70qu8i63qjekls2kmub1jp3pve1gg3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.icaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9u7HhbPGZ6DT2tLVSjIlzMpT24qtirVM',
    appId: '1:705843360963:web:8ad352687faf2a7c8a5e76',
    messagingSenderId: '705843360963',
    projectId: 'my-ica-3101',
    authDomain: 'my-ica-3101.firebaseapp.com',
    storageBucket: 'my-ica-3101.firebasestorage.app',
  );
}
